name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        description: 'Api Url'
        required: true
      key:
        type: string
        description: 'Api Key'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Api Url
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: app/src/main/res/values/strings.xml
          oldString: 'API_URL'
          newString: ${{ github.event.inputs.url }}
      - name: Setup Api Key
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: app/src/main/res/values/strings.xml
          oldString: 'API_KEY'
          newString: ${{ github.event.inputs.key }}
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build release APK
        run: ./gradlew assembleRelease
      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
      - name: Sign APK with keystore
        id : sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
