name: Build and Release APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build release APK
        run: ./gradlew assembleRelease
      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
      - name: Release signed APK
        uses: MicahSphelele/action-publish-signed-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          FILE_DIR: ${{ steps.sign_app.outputs.signedReleaseFile }}
